### ISSUE TITLE
项目启动后无法正常运行,只能绘画，不能仿真

### ISSUE THREAD

**Issue by Maicius** [mspenn/Sketch2D#1]
## 运行环境：

win 10 + VS2013 update 5 + cocos2d-x-v3.10

## 问题描述：

项目成功编译并运行，进入train和Game选项，train中一切正常，可以保存gesture，game中可以自由绘画，但是点击绿色的按钮（应该是运行吧）后，绘画的痕迹消失，点击暂停（黄色按钮）后，又能看到绘画的痕迹。即，只能绘画，不能仿真

## 运行截图：
![image](https://user-images.githubusercontent.com/17958115/50897207-636f1000-1446-11e9-9282-5e996dd1b525.png)

![image](https://user-images.githubusercontent.com/17958115/50897373-e3957580-1446-11e9-8509-5f2a6fd1ac6e.png)

请问是不是项目配置错误，缺少资源导致的？能不能提供一份运行说明文档？

**Comment by mspenn** [comment]
有一个遗留问题，就是每次画完一个图形需要按一下 **Enter** 确认，然后左上角会有识别成功失败的提示（当时写的比较仓促，😜）。
Resources目录里面已经提供了一些基础的识别数据，不需要训练也是可以识别项目主页中展示的图形的。

**看看是不是没按Enter导致没有成功识别图形捏///**

**Comment by Maicius** [comment]
谢谢学长，确实是这样的！
